version: '3'

services:
    db:
        image: postgres:alpine
        ports:
            - 54321:5432
    node:
        build: .
        command: /bin/sh -c "sleep 7;node_modules/.bin/nodemon index.js"
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
        entrypoint: ["sh","/code/entrypoint.sh"]
